# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatbot_pb2 as chatbot__pb2


class ChatbotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSQL = channel.unary_unary(
                '/chatbot.ChatbotService/GenerateSQL',
                request_serializer=chatbot__pb2.UserQuery.SerializeToString,
                response_deserializer=chatbot__pb2.SQLResponse.FromString,
                )
        self.FormatResults = channel.unary_unary(
                '/chatbot.ChatbotService/FormatResults',
                request_serializer=chatbot__pb2.QueryResults.SerializeToString,
                response_deserializer=chatbot__pb2.FormattedResponse.FromString,
                )


class ChatbotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateSQL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FormatResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatbotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSQL': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSQL,
                    request_deserializer=chatbot__pb2.UserQuery.FromString,
                    response_serializer=chatbot__pb2.SQLResponse.SerializeToString,
            ),
            'FormatResults': grpc.unary_unary_rpc_method_handler(
                    servicer.FormatResults,
                    request_deserializer=chatbot__pb2.QueryResults.FromString,
                    response_serializer=chatbot__pb2.FormattedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatbot.ChatbotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatbotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateSQL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatbot.ChatbotService/GenerateSQL',
            chatbot__pb2.UserQuery.SerializeToString,
            chatbot__pb2.SQLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FormatResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatbot.ChatbotService/FormatResults',
            chatbot__pb2.QueryResults.SerializeToString,
            chatbot__pb2.FormattedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
